name: morphct-ex
channels:
- conda-forge
dependencies:
- blas=*=openblas
- cython=0.29
- ele=0.2.0
- freud=2.6.2
- gsd=2.4.2
- h5py=2.10
- hdf5=1.10
- ipython=7.10.0 
- jupyterlab=3.0.9
- matplotlib=3.4.2
- mbuild=0.13.1
- nodejs>=10
- numpy=1.21
- openbabel=3.1.1
- pip=21.0.1
- py3dmol=0.8.0
- python=3.7
- rdkit
- scipy=1.7
- pip:
  - pyscf==1.7
  - git+https://github.com/cmelab/grits
